/* GENERATED by scripts/ingest-media.cjs — do not edit by hand.
   Re-run the script after adding photography or film to the source folder. */

export type MediaAsset = {
  slug: string;
  source: string;
  kind: "image" | "video";
  src?: string;
  width?: number;
  height?: number;
  widths?: number[];
  lqip?: string;
};

export const MEDIA: Record<string, MediaAsset> = {
  "1767372347865-2": {
    "slug": "1767372347865-2",
    "source": "1767372347865 2.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwBQCdASoWACEAPuFkok4opiMiNVv8ARAcCWcAzrAhYXm9yewBmam9nI4etBo6EkMPfljlpIAA/uqC/IgVMFSbPOzKHlJgv99JH7db7DLDaoZlPSCSTZNUyOvtJDEGl5mkxX7+ociZAAAA"
  },
  "1767531220079": {
    "slug": "1767531220079",
    "source": "1767531220079.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADwBQCdASoWACEAPulmpk4pJiOiNVv4ASAdCWQAt7ghX+PgpK8b19ST+iKt/YuPlChiGu5Yd5cEIAD+8qtYyNsEu+HpJaqyydSjX8yn7ZtiOI6GRcE0fQbBD91rD6qyqzIuOwHozx0Pka2tKYZZ9bmj+3VxVMdlLDJBdFGCM9meN8cohwNF94KZzipvFoLEIXAAAA=="
  },
  "1767531220127": {
    "slug": "1767531220127",
    "source": "1767531220127.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAACwBQCdASoWACEAPvVssFAqpiSiqqoBUB6JYgCdM1XBh6VdEAn6QAeE5mgsuIrUoKGW40IKZtAA0gYiyUrIEokqqfcyFedVwqWCvfk1Yfe+uQYZWv6pUJfQrOcJwoc4N0NhAUzSlI48+xIm2uGS5s3hjH3SUcxskjEAVByUgNSOT9rNseUp9U5q4v73Sfwd60+LEIchwwNPShWgu03OkUhUrr06cEcAAAA="
  },
  "1767531220533": {
    "slug": "1767531220533",
    "source": "1767531220533.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADwBQCdASoWACEAPvVorU6qpiSiMBVaqVAeiUAVJPFAHCuy4wkzMMzVCdrFJCOcgzNjwWnoaxdGAAD+12mejNcR2h4qCa8zwien/SUHf3hGcZolO0DRpxkMVqEVo9hDy7bASe41QHjHR/CM6YdwmLcYQOkF8IHOMIR35OhBoFrW2amf7L5AflAP7ih+1/rYuEJ5UH4585zxwBCQ0XMbaGjAcXwEAA=="
  },
  "1767551647754": {
    "slug": "1767551647754",
    "source": "1767551647754.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAABQBQCdASoWACEAPuFeok4opSOiNVv8ARAcCWUA0JAhXyOYq/5N/nsSGMTt4WNeuKOf4wAA/taAbe68fHEDEyLP0FWIXRuOH7/23ib/RsbkOCQjIKcEVqN7CuspzPJo+xT/sRZGqwT5kjPvBQAAAA=="
  },
  "1767615547311": {
    "slug": "1767615547311",
    "source": "1767615547311.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAQBgCdASoWACEAPvVsrVCqpiQisBVYAVAeiWMArDNkBIeT62GbSdeu89MX/73XWSbMntkZIOQJLIAA/ssmuNjRyyMQ7NGsBOpxP8v9lRClAmZ17WJ0VcDvJbmqku7EEMHGoXPDH+EtEYmcTC9f1wumPeBBaFiJLwXHt9RhgzyFSrp4BQNFvMAA"
  },
  "img-5366": {
    "slug": "img-5366",
    "source": "IMG_5366.JPG",
    "kind": "image",
    "width": 2334,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAADQBQCdASoWACEAPuVmok4pJiMiNVgMASAciWUAznQWbng0gKpomtZ20KIEhfVAeq1fYfLaQBwAAP7pcsLr0uJWgKCKVzBDTdzH1HA67wirhY8coTidrtr6/Iux0Ho/9K2ImQUsVZ0BHSmr9pSrpAeou0XPitESuwrzFA7p5E3o6plJIe0j/BsAAAA="
  },
  "img-5387": {
    "slug": "img-5387",
    "source": "IMG_5387.PNG",
    "kind": "image",
    "width": 1024,
    "height": 1535,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRqAAAABXRUJQVlA4IJQAAABwBQCdASoWACEAPt1aoE4opSMiNUwBEBuJQBcGA+EuUFnvvw4zfClR/xTxQVB3vUMpakNAANsi1eeFKeiLPeSjqDelg/WQRubghGA7uE9JU3EN+2CyTCsa0VQGctXYcOxFABg76tcPvwDFQtEIz94tsFQRE+Ct0917wuWh2sZV7n5/EDJ76FTIQjU7l/KPHrBduAAA"
  },
  "img-5389": {
    "slug": "img-5389",
    "source": "IMG_5389.PNG",
    "kind": "image",
    "width": 1024,
    "height": 1535,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAACQBQCdASoWACEAPvVwr1EqpiQipWzJUB6JZwDJEAZHrSYg52KPgd7ULdhrxN+od81wwNwRAAD+6pKncB/PSG1AjIu07V+hrybcicSlJMhviXa/7DbMvclW9T4pVLn/S5SIKhHK5apMWYWDY0o98tfesZqPu6/CkuTI6W7Lfq+5/pbd+VNgHkM9KwAAAA=="
  },
  "img-5466": {
    "slug": "img-5466",
    "source": "IMG_5466.JPG",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQBQCdASoWACEAPuVgpk4pJaOiNUgBIByJaQAAeh90sQsWDq4gtGI8xrNIQlCPqfqYAP7w0USl1n6Fj0wBkBFx2Ay9CVydiJ5OYZRl3dM1cVcBQ+baC1k0ohqzgyu8+AAAAA=="
  },
  "img-5573": {
    "slug": "img-5573",
    "source": "IMG_5573.JPG",
    "kind": "image",
    "width": 1170,
    "height": 1173,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwBACdASoWABYAPvV0slMqpqSiqAgBUB6JQBOmYAgpMMjAiY06BIBb7Derfzp4AP67uX28IONuwAUSetpia7c8ypCoY9PhmezyQ39RoMAxEef/bFhVqjjkXzwyVCTSXg+IAAAA"
  },
  "img-5586": {
    "slug": "img-5586",
    "source": "IMG_5586.JPG",
    "kind": "image",
    "width": 800,
    "height": 800,
    "widths": [
      800
    ],
    "lqip": "data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABQBQCdASoWABYAPvFoqE4ppiOiMBgMATAeCWgAACnKQX3ttrdsCvnFmveUDSv5bsha0gAA/t+FqvVG92cbiXo61jRf7fP1xHecRUGDO6Agm5lbitaGc62WZNVPdygPEabGHJtwwlAkqI71nk+WACLqWruyHcdiOFS1UAAA"
  },
  "img-5587": {
    "slug": "img-5587",
    "source": "IMG_5587.JPG",
    "kind": "image",
    "width": 800,
    "height": 800,
    "widths": [
      800
    ],
    "lqip": "data:image/webp;base64,UklGRpAAAABXRUJQVlA4IIQAAABwBQCdASoWABYAPvFirE4ppaSiMBgMATAeCUAX/YIeDXcph0+Ut552Z8Rlxot6bRgEPtuAAP7yoNabOIpigoNASo10bg3Krup1JAj8LeD8yCgsRi5z8rNCvD8WCZLVNiGEcZxC5k4bMhSdA4nVoDRYNpT/RpVxbAvHO2XkJYY817uKAAA="
  },
  "img-5596": {
    "slug": "img-5596",
    "source": "IMG_5596.JPG",
    "kind": "image",
    "width": 800,
    "height": 800,
    "widths": [
      800
    ],
    "lqip": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQBACdASoWABYAPu1gqE4ppaQiN/VYATAdiWUAvzgQ79tos+bAVPeIOnhHPHegAAD+uQaB/xQ1PiT+/b4hrrbELDtlAnqOSu5Ek9d7VcSMXBRY1kSny9IczD8AAA=="
  },
  "img-5610": {
    "slug": "img-5610",
    "source": "IMG_5610.PNG",
    "kind": "image",
    "width": 1254,
    "height": 1254,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBQCdASoWABYAPvVsrVGqpaQiqAqpUB6JQBYj5ofqAhHdjURzfG37alDrs00rxvfHYyAA/iGxkOCtYPkaIXBXhNlWnHIekP6BSMslIByMcIJ3mdwxJz5eAv+R4KR2Z82Lqmdb3VgndlvnTZKWkFoFGgA="
  },
  "img-5654": {
    "slug": "img-5654",
    "source": "IMG_5654.JPG",
    "kind": "image",
    "width": 800,
    "height": 800,
    "widths": [
      800
    ],
    "lqip": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBQCdASoWABYAPvVorVAqpaQisBgIAVAeiWQAsR8zh9wXOjVnxXQsQjFbgpRyei6gNHTcAPyzGFXwyTSyIv3uNR0kmkeH1/b/iG7ZdDHL4yXGUAlhcBUMg1dWDXjpiFNcpH8huYIHZthOg6qBm04s6rFO5xgA"
  },
  "img-5656": {
    "slug": "img-5656",
    "source": "IMG_5656.JPG",
    "kind": "image",
    "width": 790,
    "height": 655,
    "widths": [
      790
    ],
    "lqip": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQBQCdASoWABIAPvVssVCqpiSiqAqpUB6JYwCxH1XBoF0V4f1vF2HP/dk/5cq2tHuSAP7TMNpjxNKeeRti11NMyzN90a1VFxsYG805O/uFT5ccWMWXt1rxoU515r5MQ3pCoAxojlnTgBxgAAA="
  },
  "img-5658": {
    "slug": "img-5658",
    "source": "IMG_5658.JPG",
    "kind": "image",
    "width": 1278,
    "height": 1278,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwBACdASoWABYAPu1mpU4ppiMiMAwBMB2JQBOgBDWQa1aIANf7y0ykOuiCAAD+M8GIa4mWuJOuvGkun8eyCkydtIwv37ioSA47F0RCVqRGzWLmUdxtnxSvjhDmeiAA"
  },
  "img-5660": {
    "slug": "img-5660",
    "source": "IMG_5660.JPG",
    "kind": "image",
    "width": 720,
    "height": 1280,
    "widths": [
      720
    ],
    "lqip": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBQCdASoWACcAPvVeqU4qpKOiNVgIAVAeiWgAv2uYS2+ZSZi4oSHWixh80fmvmlQZ8zI56AAA/v5teuX97iZ7yANAKn85sIiPprGCaYA3EgaejJ1cPzywmm8u+0fwQiTaw9cGuFlhms3YQ5lcDtfyeq7tXtqfiAAAAA=="
  },
  "img-5667": {
    "slug": "img-5667",
    "source": "IMG_5667.PNG",
    "kind": "image",
    "width": 941,
    "height": 1672,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAACwBgCdASoWACcAPvVyrlEqpyQiqrgKAVAeiUAXry2gICBNwL68XIW3KqU5cDRicF7QSdD2lzdxC/I0lV5hAAD+4vWX3wAol0GPNhkHE1+RzwDR2fR+8Hym4h09XvFSgINmmuTWPmenLy5opcSpS19WAw8pBT21k2c5OI2XjyZrD6z0H7ad2F4xq081Ywuw6eQAAA=="
  },
  "img-5708": {
    "slug": "img-5708",
    "source": "IMG_5708.JPG",
    "kind": "image",
    "width": 832,
    "height": 1248,
    "widths": [
      832
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACwBACdASoWACEAPu1iqU4ppaQiNVgIATAdiWcAxnwcuSg2Py51YfdkTuKtEZM4AP7pDD6GWA8Y/bfoqdtuz+b3N5lXzk5g30/7M7iQjmDmmJLeBLlS34cTL+gISzIO33P/8WSp61fTl8cQ+rEAAA=="
  },
  "img-5713": {
    "slug": "img-5713",
    "source": "IMG_5713.PNG",
    "kind": "image",
    "width": 1024,
    "height": 1535,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAACQBQCdASoWACEAPu1mpE4ppiMiNVgIATAdiWcA0YAN7wuqXrH7GW+ZXfj7IIQkm48MWMUzYAD+tUPAFUSqML2JWzVIrXHL8veydnmz1EH9bXJ+kOSOvLp79+252DZNXJk2O+nA/PXywUBQ9LgAAA=="
  },
  "img-5714": {
    "slug": "img-5714",
    "source": "IMG_5714.PNG",
    "kind": "image",
    "width": 1024,
    "height": 1535,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABwBQCdASoWACEAPvFapk4ppKMiNVgMATAeCWcAzygUHhf7jdnuNcTylzeLKDojsp7mnmUAAP5emloVeORTp/qvnaml9pWnh356ITBBuAKeDtwwVcNxHlULwFVDNrBgO5T4ZkAwoooHv4VR0NPTOfjGoQ1JpSgAAAA="
  },
  "img-5733": {
    "slug": "img-5733",
    "source": "IMG_5733.JPG",
    "kind": "image",
    "width": 832,
    "height": 1248,
    "widths": [
      832
    ],
    "lqip": "data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBQCdASoWACEAPvVip06qpSMiMBqqqVAeiWUAygAWDsINutc6YNWIiiQ1tkrCtyYAAP6dgn9XmZsN+dhHV3YXluIHyCwQq0ZdX39svAhx5af5U2KDnNcrjE1Ae5tvoUvuNbKm+Qv1COsa8AAAAA=="
  },
  "img-5734": {
    "slug": "img-5734",
    "source": "IMG_5734.JPG",
    "kind": "image",
    "width": 832,
    "height": 1248,
    "widths": [
      832
    ],
    "lqip": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAAAwBgCdASoWACEAPu1eqU4ppSQiMBqtUTAdiWcAx2wWYRUL0MjgfbwcBwV/rJTaK65YEBrrm7UcAWAAAP65oV2AqPOQ/bdBJp1/UECErCs81gOfd6On5J7Zom7/pEA1Z6wkU6RQ9vulQffEcK66IAAA"
  },
  "img-5895": {
    "slug": "img-5895",
    "source": "IMG_5895.JPG",
    "kind": "image",
    "width": 1080,
    "height": 1080,
    "widths": [
      900
    ],
    "lqip": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQBACdASoWABYAPuliqE4pJaQiMAwBIB0JQAALfRVzQtGIVasIY4MNuvKgVAAA/upuDp33mCRZqJfDpdYLnrScfBU2NXqbErriwLxVk3Q4abwCReZkbffmgRKeJuPEAAA="
  },
  "kal03419": {
    "slug": "kal03419",
    "source": "KAL03419.jpg",
    "kind": "image",
    "width": 2333,
    "height": 3500,
    "widths": [
      900,
      1600
    ],
    "lqip": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAABQBQCdASoWACEAPvVmqU6qpaOiNVQIAVAeiUAY5PYACSR3zlQK+uScVJT4v3X7m+Qg9AAAc3FvSo2GtFqnR7tgyw8pO+vRIQoj/ihgQIYy9B7vyGT006wMcNVpRfGoJYwh8/gUbUCStY4JRfy+xad7/dQC81kkg9NCTmilAqZvO3fk72AAAA=="
  }
};

export const asset = (slug: string): MediaAsset | undefined => MEDIA[slug];
