/**
 * NEOYO — media ingestion.
 *
 * Re-runnable. Drop new photography or film into the source folder and run:
 *   node scripts/ingest-media.cjs "C:/path/to/source"
 *
 * Produces, for every image, responsive AVIF + WebP at three widths plus a
 * tiny blurred LQIP data URI, and writes lib/media.generated.ts with the
 * dimensions and placeholder for each asset. Video files are copied through
 * untouched and recorded in the same manifest.
 */
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const SRC = process.argv[2] || "C:/Users/HP/Videos/CAPCUT EDITS";
const ROOT = path.join(__dirname, "..");
const OUT_DIR = path.join(ROOT, "public", "media");
const MANIFEST = path.join(ROOT, "lib", "media.generated.ts");

// Frames are shown full-bleed and cropped, so the pixels that survive are a
// fraction of the file and any softness shows. Four widths, capped at the
// source's own resolution — `withoutEnlargement` stops us inventing detail.
const WIDTHS = [800, 1400, 2000, 2600];
const VIDEO_RE = /\.(mp4|webm|mov|m4v)$/i;
const IMAGE_RE = /\.(jpe?g|png|webp|avif)$/i;

const slugify = (file) =>
  path
    .basename(file, path.extname(file))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

(async () => {
  if (!fs.existsSync(SRC)) {
    console.error("Source folder not found:", SRC);
    process.exit(1);
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const files = fs.readdirSync(SRC).sort();
  const entries = [];

  for (const file of files) {
    const abs = path.join(SRC, file);
    if (!fs.statSync(abs).isFile()) continue;
    const slug = slugify(file);

    /* ---------------- video: copy through ---------------- */
    if (VIDEO_RE.test(file)) {
      const ext = path.extname(file).toLowerCase();
      const dest = path.join(OUT_DIR, slug + ext);
      fs.copyFileSync(abs, dest);
      entries.push({ slug, source: file, kind: "video", src: `/media/${slug}${ext}` });
      console.log("video   ", file, "->", slug + ext);
      continue;
    }

    if (!IMAGE_RE.test(file)) continue;

    /* ---------------- image: responsive derivatives ---------------- */
    const image = sharp(abs, { failOn: "none" }).rotate(); // honour EXIF orientation
    const meta = await image.metadata();

    // Every standard width the source can actually satisfy, plus the
    // source's own width when it sits meaningfully above the largest of
    // them — on a dense display that last 15% of linear resolution is the
    // difference between a photograph and a slightly soft one. Never
    // upscale: a srcset descriptor that claims pixels it does not have is
    // a lie the browser will act on.
    const usable = WIDTHS.filter((w) => w <= meta.width);
    const largest = usable.length ? usable[usable.length - 1] : 0;
    const widths = usable.length
      ? meta.width > largest * 1.1
        ? [...usable, meta.width]
        : usable
      : [meta.width];
    const made = [];

    for (const w of widths) {
      for (const [fmt, opts] of [
        // 4:4:4 keeps the chroma intact. Under the default 4:2:0 the gold
        // hardware and the red satin lose their edges at this scale.
        ["avif", { quality: 62, effort: 5, chromaSubsampling: "4:4:4" }],
        ["webp", { quality: 86 }],
      ]) {
        const name = `${slug}-${w}.${fmt}`;
        const dest = path.join(OUT_DIR, name);
        if (!fs.existsSync(dest)) {
          await sharp(abs, { failOn: "none" })
            .rotate()
            // Lanczos over the default, then a light unsharp pass. Any
            // downscale softens, and these are read at full screen.
            .resize(w, null, { withoutEnlargement: true, kernel: "lanczos3" })
            .sharpen({ sigma: 0.6, m1: 0.4, m2: 0.6 })
            .toFormat(fmt, opts)
            .toFile(dest);
        }
      }
      made.push(w);
    }

    // LQIP — a 22px blurred frame, inlined so the slide never paints empty.
    const lqip = await sharp(abs, { failOn: "none" })
      .rotate()
      .resize(22, null)
      .blur(1.4)
      .webp({ quality: 38 })
      .toBuffer();

    entries.push({
      slug,
      source: file,
      kind: "image",
      width: meta.width,
      height: meta.height,
      widths: made,
      lqip: `data:image/webp;base64,${lqip.toString("base64")}`,
    });
    console.log("image   ", file.padEnd(24), `${meta.width}x${meta.height}`, "->", made.join("/"));
  }

  const body = `/* GENERATED by scripts/ingest-media.cjs — do not edit by hand.
   Re-run the script after adding photography or film to the source folder. */

export type MediaAsset = {
  slug: string;
  source: string;
  kind: "image" | "video";
  src?: string;
  width?: number;
  height?: number;
  widths?: number[];
  lqip?: string;
};

export const MEDIA: Record<string, MediaAsset> = ${JSON.stringify(
    Object.fromEntries(entries.map((e) => [e.slug, e])),
    null,
    2
  )};

export const asset = (slug: string): MediaAsset | undefined => MEDIA[slug];
`;

  fs.writeFileSync(MANIFEST, body, "utf8");
  console.log("\nwrote", path.relative(ROOT, MANIFEST), `— ${entries.length} assets`);
})();
