/**
 * NEOYO — media ingestion.
 *
 * Re-runnable. Drop new photography or film into the source folder and run:
 *   node scripts/ingest-media.cjs "C:/path/to/source"
 *
 * Produces, for every image, responsive AVIF + WebP at three widths plus a
 * tiny blurred LQIP data URI, and writes lib/media.generated.ts with the
 * dimensions and placeholder for each asset. Video files are copied through
 * untouched and recorded in the same manifest.
 */
const sharp = require("sharp");
const fs = require("fs");
const path = require("path");

const SRC = process.argv[2] || "C:/Users/HP/Videos/CAPCUT EDITS";
const ROOT = path.join(__dirname, "..");
const OUT_DIR = path.join(ROOT, "public", "media");
const MANIFEST = path.join(ROOT, "lib", "media.generated.ts");

const WIDTHS = [900, 1600, 2400];
const VIDEO_RE = /\.(mp4|webm|mov|m4v)$/i;
const IMAGE_RE = /\.(jpe?g|png|webp|avif)$/i;

const slugify = (file) =>
  path
    .basename(file, path.extname(file))
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

(async () => {
  if (!fs.existsSync(SRC)) {
    console.error("Source folder not found:", SRC);
    process.exit(1);
  }
  fs.mkdirSync(OUT_DIR, { recursive: true });

  const files = fs.readdirSync(SRC).sort();
  const entries = [];

  for (const file of files) {
    const abs = path.join(SRC, file);
    if (!fs.statSync(abs).isFile()) continue;
    const slug = slugify(file);

    /* ---------------- video: copy through ---------------- */
    if (VIDEO_RE.test(file)) {
      const ext = path.extname(file).toLowerCase();
      const dest = path.join(OUT_DIR, slug + ext);
      fs.copyFileSync(abs, dest);
      entries.push({ slug, source: file, kind: "video", src: `/media/${slug}${ext}` });
      console.log("video   ", file, "->", slug + ext);
      continue;
    }

    if (!IMAGE_RE.test(file)) continue;

    /* ---------------- image: responsive derivatives ---------------- */
    const image = sharp(abs, { failOn: "none" }).rotate(); // honour EXIF orientation
    const meta = await image.metadata();

    const widths = WIDTHS.filter((w) => w <= meta.width).concat(
      WIDTHS.every((w) => w > meta.width) ? [meta.width] : []
    );
    const made = [];

    for (const w of widths) {
      for (const [fmt, opts] of [
        ["avif", { quality: 52, effort: 4 }],
        ["webp", { quality: 78 }],
      ]) {
        const name = `${slug}-${w}.${fmt}`;
        const dest = path.join(OUT_DIR, name);
        if (!fs.existsSync(dest)) {
          await sharp(abs, { failOn: "none" })
            .rotate()
            .resize(w, null, { withoutEnlargement: true })
            .toFormat(fmt, opts)
            .toFile(dest);
        }
      }
      made.push(w);
    }

    // LQIP — a 22px blurred frame, inlined so the slide never paints empty.
    const lqip = await sharp(abs, { failOn: "none" })
      .rotate()
      .resize(22, null)
      .blur(1.4)
      .webp({ quality: 38 })
      .toBuffer();

    entries.push({
      slug,
      source: file,
      kind: "image",
      width: meta.width,
      height: meta.height,
      widths: made,
      lqip: `data:image/webp;base64,${lqip.toString("base64")}`,
    });
    console.log("image   ", file.padEnd(24), `${meta.width}x${meta.height}`, "->", made.join("/"));
  }

  const body = `/* GENERATED by scripts/ingest-media.cjs — do not edit by hand.
   Re-run the script after adding photography or film to the source folder. */

export type MediaAsset = {
  slug: string;
  source: string;
  kind: "image" | "video";
  src?: string;
  width?: number;
  height?: number;
  widths?: number[];
  lqip?: string;
};

export const MEDIA: Record<string, MediaAsset> = ${JSON.stringify(
    Object.fromEntries(entries.map((e) => [e.slug, e])),
    null,
    2
  )};

export const asset = (slug: string): MediaAsset | undefined => MEDIA[slug];
`;

  fs.writeFileSync(MANIFEST, body, "utf8");
  console.log("\nwrote", path.relative(ROOT, MANIFEST), `— ${entries.length} assets`);
})();
